export interface ColumnConfig {
  id: string;
  label: string;
  alwaysVisible?: boolean;
}

export interface PageConfig {
  id: string;
  name: string;
  /** Translation key override for sidebar label. Falls back to aside.{id} */
  labelKey?: string;
  columns: ColumnConfig[];
}

export const TABLE_PAGES_CONFIG: PageConfig[] = [
  {
    id: "users",
    name: "Foydalanuvchilar",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "full_name", label: "F.I.Sh" },
      { id: "phone", label: "Telefon" },
      { id: "role", label: "Rol" },
      { id: "status", label: "Holati" },
      { id: "branch", label: "Filial" },
      { id: "username", label: "Login" },
      { id: "pinfl", label: "JSHSHIR" },
      { id: "type", label: "Turi" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "branches",
    name: "Filiallar",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "name", label: "Nomi" },
      { id: "address", label: "Manzil" },
      { id: "city", label: "Shahar" },
      { id: "director_name", label: "Direktor" },
      { id: "email", label: "Email" },
      { id: "phone", label: "Telefon" },
      { id: "account_number", label: "Hisob raqami" },
      { id: "postal_code", label: "Pochta indeksi" },
      { id: "legal_name", label: "Yuridik nomi" },
      { id: "inn", label: "INN" },
      { id: "bank_name", label: "Bank nomi" },
      { id: "mfo", label: "MFO" },
      { id: "oked", label: "OKED" },
      { id: "is_active", label: "Holati" },
      { id: "has_contract", label: "Shartnoma" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "regions",
    name: "Viloyatlar",
    labelKey: "aside.regions",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "name", label: "Nomi" },
      { id: "code", label: "Kodi" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "districts",
    name: "Tumanlar",
    labelKey: "aside.districts",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "name", label: "Nomi" },
      { id: "region", label: "Viloyat" },
      { id: "code", label: "Kodi" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "departments",
    name: "Bo'limlar",
    labelKey: "aside.departments",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "name", label: "Nomi" },
      { id: "code", label: "Kodi" },
      { id: "branch", label: "Filial" },
      { id: "manager", label: "Manager" },
      { id: "is_active", label: "Holati" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "attendance",
    name: "Davomat",
    labelKey: "aside.attendance",
    columns: [
      { id: "id", label: "ID" },
      { id: "full_name", label: "F.I.Sh" },
      { id: "position", label: "Lavozim" },
      { id: "date", label: "Sana" },
      { id: "status", label: "Holat" },
      { id: "check_in", label: "Kelish vaqti" },
      { id: "check_out", label: "Ketish vaqti" },
      { id: "comment", label: "Izoh" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
    ],
  },
  {
    id: "operators",
    name: "Operatorlar",
    labelKey: "aside.operators",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "full_name", label: "F.I.Sh" },
      { id: "branch", label: "Filial" },
      { id: "login", label: "Login" },
      { id: "password", label: "Parol" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "courses",
    name: "Kurslar",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "name", label: "Nomi" },
      { id: "branches", label: "Filiallar" },
      { id: "levels", label: "Darajalar" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "levels",
    name: "Darajalar",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "name", label: "Nomi" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "positions",
    name: "Lavozimlar",
    labelKey: "aside.positions",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "name", label: "Nomi" },
      { id: "department", label: "Bo'lim" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "students",
    name: "O'quvchilar",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "full_name", label: "F.I.Sh" },
      { id: "phone", label: "Telefon raqami" },
      { id: "parents_phone", label: "Ota-onasi raqami" },
      { id: "pinfl", label: "JSHSHIR" },
      { id: "group", label: "Guruh" },
      { id: "status", label: "Status" },
      { id: "balance", label: "Balans" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "teachers",
    name: "O'qituvchilar",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "full_name", label: "F.I.Sh" },
      { id: "phone", label: "Telefon" },
      { id: "branch", label: "Filial" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "rooms",
    name: "Xonalar",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "branch", label: "Filial" },
      { id: "name", label: "Xona nomi" },
      { id: "capacity", label: "Sig'im" },
      { id: "floor", label: "Qavat" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "sources",
    name: "Manbalar",
    labelKey: "aside.sources",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "name", label: "Nomi" },
      { id: "link", label: "Havola" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "payments",
    name: "To'lovlar",
    labelKey: "aside.payments",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "full_name", label: "F.I.Sh" },
      { id: "amount", label: "Summa" },
      { id: "payment_method", label: "To'lov turi" },
      { id: "branch", label: "Filial" },
      { id: "course", label: "Kurs" },
      { id: "teacher", label: "O'qituvchi" },
      { id: "group", label: "Guruh" },
      { id: "payment_date", label: "To'lov sanasi" },
      { id: "payment_period", label: "To'lov davri" },
      { id: "cashier", label: "Kassir" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "expenseCategories",
    name: "Chiqimlar kategoriyasi",
    labelKey: "aside.expenseCategory",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "name", label: "Nomi" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "expenseSubCategories",
    name: "Chiqimlar podkategoriyasi",
    labelKey: "aside.expenseSubCategory",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "name", label: "Nomi" },
      { id: "category", label: "Kategoriya" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "expenses",
    name: "Chiqim kiritish",
    labelKey: "aside.expenseCreate",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "category", label: "Kategoriya" },
      { id: "subcategory", label: "Podkategoriya" },
      { id: "cashier", label: "Kassir" },
      { id: "amount", label: "Summa" },
      { id: "expense_date", label: "Sana" },
      { id: "branch", label: "Filial" },
      { id: "info", label: "Izoh" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "classes",
    name: "Guruhlar",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "name", label: "Guruh nomi" },
      { id: "course", label: "Kurs" },
      { id: "teacher", label: "O'qituvchi" },
      { id: "room", label: "Xona" },
      { id: "days", label: "Kunlar" },
      { id: "time", label: "Vaqt" },
      { id: "students_count", label: "O'quvchilar soni" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "roles",
    name: "Ro'llar",
    labelKey: "aside.roles",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "name", label: "Nomi" },
      { id: "permissions_count", label: "Huquqlar soni" },
      { id: "created_at", label: "Yaratilgan sana" },
      { id: "updated_at", label: "O'zgartirilgan sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
];
