export const TABLE_PAGES_CONFIG = [
  {
    id: "users",
    name: "Foydalanuvchilar",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "full_name", label: "F.I.Sh" },
      { id: "phone", label: "Telefon" },
      { id: "role", label: "Rol" },
      { id: "status", label: "Holati" },
      { id: "branch", label: "Filial" },
      { id: "username", label: "Login" },
      { id: "date", label: "Sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "branches",
    name: "Filiallar",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "address", label: "Manzil" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "classes",
    name: "Guruhlar",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "name", label: "Guruh nomi" },
      { id: "course", label: "Kurs" },
      { id: "teacher", label: "O'qituvchi" },
      { id: "room", label: "Xona" },
      { id: "days", label: "Kunlar" },
      { id: "time", label: "Vaqt" },
      { id: "students_count", label: "O'quvchilar soni" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "courses",
    name: "Kurslar",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "name", label: "Nomi" },
      { id: "branches", label: "Filiallar" },
      { id: "levels", label: "Darajalar" },
      { id: "created_at", label: "Sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "levels",
    name: "Darajalar",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "name", label: "Nomi" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "students",
    name: "O'quvchilar",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "full_name", label: "F.I.Sh" },
      { id: "phone", label: "Telefon raqami" },
      { id: "parents_phone", label: "Ota-onasi raqami" },
      { id: "pinfl", label: "JSHSHIR" },
      { id: "group", label: "Guruh" },
      { id: "status", label: "Status" },
      { id: "balance", label: "Balans" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "teachers",
    name: "O'qituvchilar",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "full_name", label: "F.I.Sh" },
      { id: "phone", label: "Telefon" },
      { id: "branch", label: "Filial" },
      { id: "date", label: "Sana" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
  {
    id: "rooms",
    name: "Xonalar",
    columns: [
      { id: "checkbox", label: "Checkbox", alwaysVisible: true },
      { id: "id", label: "ID" },
      { id: "branch", label: "Filial" },
      { id: "name", label: "Xona nomi" },
      { id: "capacity", label: "Sig'im" },
      { id: "floor", label: "Qavat" },
      { id: "actions", label: "Harakatlar", alwaysVisible: true },
    ],
  },
];
